# Generated by Django 5.0.1 on 2024-01-26 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255)),
                ('attendance_average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assignment_completion', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('cohort', models.CharField(max_length=20)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Basic Detail',
                'verbose_name_plural': 'Basic Details',
            },
        ),
        migrations.CreateModel(
            name='weekly_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('present', models.IntegerField()),
                ('absent', models.IntegerField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nebula_app.basic_detail')),
            ],
            options={
                'verbose_name': 'weekly_attendance',
                'verbose_name_plural': 'weekly_attendance',
            },
        ),
    ]
