# Generated by Django 5.0.1 on 2024-01-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_detail',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
