# Generated by Django 5.0.1 on 2024-01-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nebula_app', '0002_alter_basic_detail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_detail',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, unique=True),
        ),
    ]
